SRC/BanVeMayBay/BanVeMayBay/Models/topic.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public topic()
        {
            this.posts = new HashSet<post>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public int parentid { get; set; }
        public int orders { get; set; }
        public System.DateTime created_at { get; set; }
        public int created_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public int updated_by { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post> posts { get; set; }
        public virtual user user { get; set; }
    }
}

SRC/BanVeMayBay/BanVeMayBay/Areas/Admin/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanVeMayBay.Common;
using BanVeMayBay.DesignPattern.Singleton;
using BanVeMayBay.Models;

namespace BanVeMayBay.Areas.Admin.Controllers
{
    public class TopicController : BaseController
    {
        private BANVEMAYBAYEntities db = new BANVEMAYBAYEntities();


        public TopicController()
        {
            TopicSingleton.Instance.Init(db);
        }

        // GET: Admin/Topic
        public ActionResult Index()
        {
            
            var list = TopicSingleton.Instance.listTopic.Where(m => m.status !=0).OrderByDescending(m => m.ID).ToList();
            return View(list);
        }

        // GET: Admin/Topic/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            topic mtopic = TopicSingleton.Instance.listTopic.Find(tp => tp.ID == id);
            if (mtopic == null)
            {
                return HttpNotFound();
            }
            return View(mtopic);
        }

        // GET: Admin/Topic/Create
        public ActionResult Create()
        {
            ViewBag.listtopic = TopicSingleton.Instance.listTopic.Where(m => m.status != 0).ToList();
            return View();
        }

        // POST: Admin/Topic/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(topic mtopic)
        {
            if (ModelState.IsValid)
            {
                //category
                string slug = Mystring.ToSlug(mtopic.name.ToString());
                mtopic.slug = slug;
                mtopic.created_at = DateTime.Now;
                mtopic.updated_at = DateTime.Now;
                mtopic.created_by = int.Parse(Session["Admin_id"].ToString());
                mtopic.updated_by = int.Parse(Session["Admin_id"].ToString());
                db.topics.Add(mtopic);
                db.SaveChanges();
                TopicSingleton.Instance.UpdateSingleton(db);
                Message.set_flash("More success", "success");
                return RedirectToAction("Index");
            }
            Message.set_flash("More failure", "danger");
            ViewBag.listtopic = db.topics.Where(m => m.status != 0).ToList();
            return View(mtopic);
        }

        // GET: Admin/Topic/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            topic mtopic = TopicSingleton.Instance.listTopic.Find(tp => tp.ID == id);
            if (mtopic == null)
            {
                return HttpNotFound();
            }
            ViewBag.listtopic = TopicSingleton.Instance.listTopic.Where(m => m.status != 0).ToList();
            return View(mtopic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( topic mtopic)
        {
            if (ModelState.IsValid)
            {
                string slug = Mystring.ToSlug(mtopic.name.ToString());


                mtopic.updated_at = DateTime.Now;
                mtopic.updated_by = int.Parse(Session["Admin_id"].ToString());
                db.Entry(mtopic).State = EntityState.Modified;
                db.SaveChanges();
                TopicSingleton.Instance.UpdateSingleton(db);
                return RedirectToAction("Index");
            }

            ViewBag.listtopic = TopicSingleton.Instance.listTopic.Where(m => m.status != 0).ToList();
            return View(mtopic);

        }

        public ActionResult Status(int id)
        {
            topic mtopic = db.topics.Find(id);
            mtopic.status = (mtopic.status == 1) ? 2 : 1;
            mtopic.updated_at = DateTime.Now;
            mtopic.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mtopic).State = EntityState.Modified;
            db.SaveChanges();
            TopicSingleton.Instance.UpdateSingleton(db);
            Message.set_flash("Status change successful", "success");
            return RedirectToAction("Index");
        }
        //trash
        public ActionResult trash()
        {
            var list = TopicSingleton.Instance.listTopic.Where(m => m.status == 0).ToList();
            return View("Trash", list);
        }
        public ActionResult Deltrash(int id)
        {
            topic mtopic = TopicSingleton.Instance.listTopic.Find(tp => tp.ID == id);
            mtopic.status = 0;
            mtopic.updated_at = DateTime.Now;
            mtopic.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mtopic).State = EntityState.Modified;
            db.SaveChanges();
            TopicSingleton.Instance.UpdateSingleton(db);
            Message.set_flash("Delete successfully", "success");
            return RedirectToAction("Index");
        }

        public ActionResult Retrash(int id)
        {
            topic mtopic = TopicSingleton.Instance.listTopic.Find(tp => tp.ID == id);
            mtopic.status = 2;
            mtopic.updated_at = DateTime.Now;
            mtopic.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mtopic).State = EntityState.Modified;
            db.SaveChanges();
            TopicSingleton.Instance.UpdateSingleton(db);
            Message.set_flash("Restore Success", "success");
            return RedirectToAction("trash");
        }
        public ActionResult deleteTrash(int id)
        {
            topic mtopic = TopicSingleton.Instance.listTopic.Find(tp => tp.ID == id);
            db.topics.Remove(mtopic);
            db.SaveChanges();
            TopicSingleton.Instance.UpdateSingleton(db);
            Message.set_flash("1 Thread has been permanently deleted", "success");
            return RedirectToAction("trash");
        }
    }
}

SRC/BanVeMayBay/BanVeMayBay/Controllers/SiteController.cs
using BanVeMayBay.Common;
using BanVeMayBay.DesignPattern.TemplateMethod;
using BanVeMayBay.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanVeMayBay.Controllers
{
    public class SiteController : TemplateMethodController
    {
        BANVEMAYBAYEntities db = new BANVEMAYBAYEntities();

        public SiteController()
        {
            var result = PrintInfo();
            Debugger.Log(1, "Logger: ", $"{result}");
        }

        public ActionResult Index()
        {
            return View();
        }
         
        [HttpPost]        
        public ActionResult flightSearch(FormCollection fc, int? page)
        {
            
            string typeTicket = fc["typeticket"];
            if (page == null) 
            { 
                page = 1; 
            }
            int pageSize = 4;
          
            int songuoi1 = int.Parse(fc["songuoi1"]);
            int songuoi2 = int.Parse(fc["songuoi2"]);
            int songuoi3 = int.Parse(fc["songuoi3"]);
            int tong = songuoi1 + songuoi2 + songuoi3;
            int songuoi = tong;
            ViewBag.songuoi = songuoi;
            string noiBay = fc["departure_address"];
            string noiVe = fc["arrival_address"];
            string ngaybay = fc["departure_date"];
           
            ViewBag.url = "chuyen-bay";

            //convert sang mm/dd/yy cho may hieu 
            DateTime ngaybay1 = DateTime.ParseExact(ngaybay, "dd/MM/yyyy", CultureInfo.InvariantCulture);

            //sang mm/dd/yy
            string ngaybay2 = ngaybay1.ToString("MM-dd-yyyy");
            DateTime ngaybay3 = DateTime.Parse(ngaybay2);
            ViewBag.noiBay = noiBay;
            ViewBag.noiVe = noiVe;
            ViewBag.ngaybay = ngaybay;
           
            // neu la ve 2 chieu
            if (typeTicket.Equals("enable"))
            {
                string ngayve = fc["arrival_date"];
                DateTime ngayden1 = DateTime.ParseExact(ngayve, "d/M/yyyy", CultureInfo.InvariantCulture);
                string ngayden2 = ngayden1.ToString("MM-dd-yyyy");
                DateTime ngayden3 = DateTime.Parse(ngayden2);
                ViewBag.ngayden = ngayve;
                ViewBag.date = ngayden3;

                if (ngaybay1 > ngayden1)
                {
                    Message.set_flash("Return date must be greater than or equal to departure date!", "danger");
                    return Redirect("~/Home/Index");
                }
                var list = db.tickets.Where(m => m.city.cityName.Contains(noiBay) && m.city1.cityName.Contains(noiVe)).
             Where(m => m.departure_date == ngaybay3).Where(m => m.status == 1).ToList();
                int pageNumber = (page ?? 1);
                return View("flightSearchReturn", list.ToPagedList(pageNumber, pageSize));
                    
                
            }
            else
            {

                //ve 1 chieu
                var list = db.tickets.Where(m => m.city.cityName.Contains(noiBay) && m.city1.cityName.Contains(noiVe)).
             Where(m => m.departure_date == ngaybay3).Where(m=>m.status==1).ToList();
                int pageNumber = (page ?? 1);
                return View("flightSearchOnway", list.ToPagedList(pageNumber, pageSize));
            
            }

        }
        
        public ActionResult return_ticket(DateTime date,string noibay, string noiden)
        {
           
            var list = db.tickets.Where(m => m.city.cityName.Contains(noiden) && m.city1.cityName.Contains(noibay)).
               Where(m => m.departure_date == date).Where(m => m.status == 1).ToList();
            return View("_returnTicket", list);
        }
        public ActionResult AllChuyenBay(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 10;
            var singleC = db.topics.Where(m => m.status == 1).Where(m => m.status == 1).First();
            ViewBag.url = "all-chuyen-bay";
            int pageNumber = (page ?? 1);
            //không biết sử dụng
            //ViewBag.breadcrumb = "Tất cả chuyến bay";//không biết sử dụng
            var list_flight = db.tickets.Where(m => m.status == 1).ToList();
            return View("allflight", list_flight.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult postOftoPic(int? page, string slug)
        {
            if (page == null) page = 1;
            int pageSize = 4;
            var singleC = db.topics.Where(m => m.status == 1 && m.slug == slug).Where(m => m.status == 1).First();
            ViewBag.nameTopic = slug;
            ViewBag.url = "tin-tuc/" + slug + "";
            int pageNumber = (page ?? 1);
            var listPost = db.posts.Where(m => m.status == 1 && m.topid == singleC.ID).OrderByDescending(m => m.ID).ToList();
            return View("postOftoPic", listPost.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult topic()
        {

            var list = db.topics.Where(m => m.status == 1).Where(m => m.status == 1).ToList();
            return View("_topic", list);
        }

        public ActionResult postSearch(string keyw, int? page)
        {
            if (page == null) page = 1;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            ViewBag.url = "tim-kiem-bai-viet?keyw=" + keyw + "";
            @ViewBag.nameTopic = "Tim kiếm từ khóa: " + keyw;
            var list = db.posts.Where(m => m.title.Contains(keyw) || m.detail.Contains(keyw)).Where(m => m.status == 1).OrderBy(m => m.ID);
            return View("postOftoPic", list.ToList().ToPagedList(pageNumber, pageSize));
        }
        public ActionResult PostDetal(string slug)
        {

            var single = db.posts.Where(m => m.status == 1 && m.slug == slug).First();
            ViewBag.Bra = single.title;
            return View("PostDetal", single);
        }
        
            public ActionResult flightDetail(int id)
        {
            var single = db.tickets.Where(m => m.status == 1 && m.id == id).First();
            return View("flightDetail", single);
        }
        public ActionResult lienHe()
        {
            var single = db.posts.Where(m => m.status == 1 && m.slug == "contact-us").First();
            return View("PostDetal", single);
        }



        public override string PrintRoutes()
        {
            return "========================" +
                "Site Controller is running!" +
                "======================";
        }

        public override string PrintDIs()
        {
            return "=================No Dependence Injection================\n";
        }
    }
}

SRC/BanVeMayBay/BanVeMayBay/Views/Site/PostDetal.cshtml
@model BanVeMayBay.Models.post
@{
    ViewBag.Title = "postOftoPic";
    Layout = "~/Views/Shared/_layOutSite.cshtml";
}
<!-- Breadcrumb -->
<!-- BreadCrumb Ends -->
<!-- Destinations -->
<section class="destinations">
    <div class="container " style="padding:20px;">
        <div class="row">
            <nav aria-label="breadcrumb">
                <ul class="breadcrumb bg-white">
                    <li class="breadcrumb-item"><a href="~/">HomePage</a></li>
                    <li class="breadcrumb-item"><a href="~/tin-tuc">News</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@ViewBag.Bra</li>
                </ul>
            </nav>
            <div class="col-md-8 bg-white">
                <div class="row">
                    <div class="col-md-12">
                        <div class="destination-outer">
                            <p style="font-weight:bold;font-size:25px;color:#ff6a00;">@Html.Raw(Model.title)</p> <br />
                            <p>@Html.Raw(Model.detail)</p>
                        </div>
                    </div>
                </div>
          
            </div>
            <div id="sidebar-sticky" class="col-md-4">
                <aside class="detail-sidebar sidebar-wrapper">
                    <div class="sidebar-item sidebar-item-dark">
                        <div class="detail-title">
                            <h3>Search</h3>
                        </div>
                        <form action="~/tim-kiem-bai-viet" method="get">
                            <div class="row">
                                <div class="form-group col-xs-12">
                                    <input type="text" class="form-control" name="keyw" placeholder="What do you want to search...">
                                </div>
                                <div class="col-xs-12">
                                    <div class="comment-btn">
                                        <button class="btn-blue ">Search</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="sidebar-item">
                        <div class="detail-title">
                            <h3>News category</h3>
                        </div>
                        <ul class="event-list">
                            @Html.Action("topic", "Site")

                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>
<!-- Destination Ends -->

SRC/BanVeMayBay/BanVeMayBay/Views/Site/_returnTicket.cshtml
@model IEnumerable<BanVeMayBay.Models.ticket>

@foreach (var item in Model)
{
<tr>
    <td class="text-center">
        <img style="width:70px;height:50px" src="~/public/images/flight/@item.airline" alt="">
    </td>
    <td>
        <h6>@item.city.cityName</h6>
        <p>Airport (@item.city.cityName)</p>
    </td>
    <td>
        <h6>@item.city1.cityName</h6>
        <P>Airport (@item.city1.cityName)</P>
    </td>
    <td>
        <h6><strong class="color-red-3">@item.price.Value.ToString("N0") $</strong></h6>
        <p class="emi">(Currency - $)</p>
    </td>
    <td>@item.ticketType</td>
    <td>
        <a href="~/chuyen-bay/@item.id">Detail</a>
    </td>


    <td>
        @Html.RadioButton("datveKH", item.id, new { name = "idTitket", required = "required" })
        @Html.Label("Book")
    </td>
</tr>
}

SRC/BanVeMayBay/BanVeMayBay/Views/Site/_topic.cshtml
@model IEnumerable<BanVeMayBay.Models.topic>

@foreach (var item in Model)
{
    <li><a href="~/tin-tuc/@item.slug"> @item.name</a></li>
}

SRC/BanVeMayBay/BanVeMayBay/Views/Site/flightSearchReturn.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<BanVeMayBay.Models.ticket>
@{
    ViewBag.Title = "flightSearch";
    Layout = "~/Views/Shared/_layOutSite.cshtml";
}
<section class="flight-destinations">
    <div class="container bg-white">
        <div class="row">
            <form action="~/Checkout/Index" method="post">
                <input type="hidden" name="songuoi" value="@ViewBag.songuoi" />
                <div class="col-md-12 col-sm-12"  style="padding-top:80px;">
                    <div class="flight-head">
                        <div class="">
                            <nav aria-label="breadcrumb">
                                <span style="font-weight:bold; font-size:22px;"><i class="fas fa-fighter-jet"></i> Choose a trip </span>
                                <span style="font-weight:bold; color:#ff6a00; font-size:22px;"> @ViewBag.noibay </span> - To -<span style="font-weight:bold; color:#ff6a00; font-size:22px;"> @ViewBag.noiVe </span><br />
                                <span style="font-weight:bold; font-size:22px;"><i class="fas fa-calendar-day"></i> Departure Date </span>
                                <span style="font-weight:bold; color:#ff0000; font-size:22px;"> @ViewBag.ngaybay </span>
                            </nav>
                        </div>
                    </div>

                    <div class="flight-table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Airline</th>
                                    <th>From</th>
                                    <th>To</th>
                                    <th>Price</th>
                                    <th>Class</th>
                                    <th>Detail</th>

                                    <th>#</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td class="text-center">
                                        <img style="width:70px;height:50px" src="~/public/images/flight/@item.airline" alt="">
                                    </td>
                                    <td>
                                        <h6>@item.city.cityName</h6>
                                        <p>Airport (@item.city.cityName)</p>
                                    </td>
                                    <td>
                                        <h6>@item.city1.cityName</h6>
                                        <P>Airport (@item.city1.cityName)</P>
                                    </td>
                                    <td>
                                        <h6><strong class="color-red-3">@item.price.Value.ToString("N0") $</strong></h6>
                                        <p class="emi">(currency - $)</p>
                                    </td>
                                    <td>@item.ticketType</td>
                                    <td>
                                        <a href="~/chuyen-bay/@item.id">Detail</a>
                                    </td>

                                    <td>
                                        @Html.RadioButton("datve", item.id, new { name = "idTitket", required = "required" })
                                        @Html.Label("Book")
                                    </td>
                                </tr>
                                }


                            </tbody>
                        </table>
                    </div>

                </div>


</div>
    </div>
</section>
    <div class="container bg-white" style="margin-bottom:50px">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="flight-head">
                    <div class="">
                        <nav aria-label="breadcrumb">
                            <span style="font-weight:bold; font-size:22px;"><i class="fas fa-fighter-jet"></i> Choose return trip </span>
                            <span style="font-weight:bold; color:#ff6a00; font-size:22px;"> @ViewBag.noive </span> - To -<span style="font-weight:bold; color:#ff6a00; font-size:22px;"> @ViewBag.noibay </span><br />
                            <span style="font-weight:bold; font-size:22px;"><i class="fas fa-calendar-day"></i> Departure Date </span>
                            <span style="font-weight:bold; color:#ff0000; font-size:22px;"> @ViewBag.ngayden </span>
                        </nav>
                    </div>
                </div>
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                <div class="flight-table">
                    <table>
                        <thead>
                            <tr>
                                <th>Airline</th>
                                <th>Departure Date</th>
                                <th>To</th>
                                <th>Price</th>
                                <th>Class</th>
                                <th>Detail</th>

                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @Html.Action("return_ticket", "Site", new { date = ViewBag.date, noibay = ViewBag.noibay, noiden = ViewBag.noiVe })
                        </tbody>
                    </table>
                </div>

                <div class="container " >
                    <div class="row">
                        <div class="col-md-10" style="padding-bottom:50px;">

                        </div>

                        <button class="btn-blue btn-red btn-style-1 " type="submit">Next</button>
                    </div>
                </div>
            </div>

            </form>
        </div>
    </div>

   
<!-- Destination Ends -->
<script>
    $("#active_@Model.PageNumber").addClass("active");

    function ajaxShowItem(t) {
        console.log(t.value)
    }
</script>

SRC/BanVeMayBay/BanVeMayBay/Views/Site/postOftoPic.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<BanVeMayBay.Models.post>
@{
    ViewBag.Title = "postOftoPic";
    Layout = "~/Views/Shared/_layOutSite.cshtml";
}
<!-- Breadcrumb -->
<!-- BreadCrumb Ends -->
<!-- Destinations -->
<section class="destinations">
    <div class="container " style="padding:20px;">
        <div class="row">
            <nav aria-label="breadcrumb">
                <ul class="breadcrumb bg-white">
                    <li class="breadcrumb-item"><a href="~/">HomePage</a></li>
                    <li class="breadcrumb-item"><a href="">News</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@ViewBag.nameTopic</li>
                </ul>
            </nav>
            <div class="col-md-8 bg-white">
                <div class="row">
                    <div class="col-md-12">
                        <div class="destination-outer">
                            @foreach (var item in Model)
                            {
                                <div class="destination-fw-item " style="padding-top:10px;">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="destination-fw-image">
                                                <img style="width:200px;height:150px;" src="~/public/images/post/@item.img" alt="Image">
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="destination-fw-desc fw-content">
                                                <h3><a href="~/chi-tiet-bai-viet/@item.slug">@item.title</a></h3>
                                                <div class="package-content">
                                                    <span>@item.created_at</span><br>
                                                                                 <p>@item.title</p>
                                                  <a href="~/chi-tiet-bai-viet/@item.slug">Read More</a>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            }


                        </div>
                    </div>
                </div>
                <div class="pagination-content text-center">
                    <ul class="pagination">


                        <li>
                            <a href="~/@ViewBag.url?page=1" class="single-btn prev-btn ">
                                <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li>
                            @{
                                var firstPage = 1;
                                if ((int)Model.PageNumber > 1)
                                {
                                    firstPage = (int)Model.PageNumber - 1;
                                }

                                var lastpage = Model.PageNumber;
                                if (lastpage < Model.PageCount)
                                {
                                    lastpage = (int)Model.PageNumber + 1;
                                }

                            }
                            <a href="~/@ViewBag.url?page=@firstPage" class="single-btn prev-btn ">
                                <i class="fa fa-angle-left" aria-hidden="true"></i>
                            </a>
                        </li>

                        @for (int i = Model.PageNumber; i <= Model.PageCount; i++)
                        {

                            if (i < Model.PageNumber + 5)
                            {
                                <li id="active_@i"><a href="~/@ViewBag.url?page=@i" class="single-btn">@i  </a></li>
                            }

                        }
                        <li>
                            <a href="~/@ViewBag.url?page=@lastpage" class="single-btn next-btn">
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li>
                            <a href="~/@ViewBag.url?page=@Model.PageCount" class="single-btn next-btn">
                                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="sidebar-sticky" class="col-md-4">
                <aside class="detail-sidebar sidebar-wrapper">
                    <div class="sidebar-item sidebar-item-dark">
                        <div class="detail-title">
                            <h3>Search</h3>
                        </div>
                        <form action="~/tim-kiem-bai-viet" method="get">
                            <div class="row">
                                <div class="form-group col-xs-12">
                                    <input type="text" class="form-control" name="keyw" placeholder="What do you want to search...">
                                </div>
                                <div class="col-xs-12">
                                    <div class="comment-btn">
                                        <button  class="btn-blue ">Search</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="sidebar-item">
                        <div class="detail-title">
                            <h3>News category</h3>
                        </div>
                        <ul class="event-list">
                          @Html.Action("topic","Site")

                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>
<!-- Destination Ends -->